name: Build

# trigger the workflow on push or pull requests
on: [push, pull_request, workflow_dispatch]

jobs:
  build-and-run-tests:
    runs-on: ubuntu-20.04     # this is a GitHub Runner, hosting the execution
    container: ubuntu:20.04   # but this is a Docker Hub container, in which everything runs

    services:
      redis:
        image: redis:7.0.12-alpine  # Docker Hub image used as a sidecar

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        apt-get -y update
        DEBIAN_FRONTEND=noninteractive apt-get -y --allow-unauthenticated --allow-downgrades --allow-remove-essential --allow-change-held-packages \
          install make gcc libevent-dev libmsgpack-dev python3.8 python3-pip curl nodejs
        update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 1
    - name: Build
      run: make
    - name: Run Webdis and test
      run: |
        ./webdis .github/workflows/webdis-ci.json
        sleep 2
        ./tests/basic.py
        ./tests/curl-tests.sh
        pip3 --no-cache-dir install -r tests/requirements.txt
        ./tests/ws-tests.py
    - name: Archive logs
      uses: actions/upload-artifact@v3
      with:
        name: webdis.log
        path: webdis.log
